### ISSUE TITLE
urllib2.HTTPError: HTTP Error 402: Payment Required

### ISSUE THREAD

**Issue by alexdefo** [videns/vulners-scanner#8]
Whats all? Project is down?

**Comment by gruz0** [comment]
+1

```bash
root@support:~/vulners-scanner# ./linuxScanner.py

             _
__   ___   _| |_ __   ___ _ __ ___
\ \ / / | | | | '_ \ / _ \ '__/ __|
 \ V /| |_| | | | | |  __/ |  \__ \
  \_/  \__,_|_|_| |_|\___|_|  |___/

==========================================
Host info - Host machine
OS Name - debian, OS Version - 8
Total found packages: 765
Traceback (most recent call last):
  File "./linuxScanner.py", line 125, in <module>
    scannerInstance.scan(checkDocker=False)
  File "./linuxScanner.py", line 110, in scan
    hostInstance = self.auditSystem(sshPrefix=None,systemInfo="Host machine")
  File "./linuxScanner.py", line 78, in auditSystem
    response = self.sendVulnRequest(url, payload)
  File "./linuxScanner.py", line 56, in sendVulnRequest
    response = urllib2.urlopen(req, json.dumps(payload).encode('utf-8'))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 402: Payment Required
```

**Comment by LanderU** [comment]
Any updates on this?

**Comment by sasha-x** [comment]
+1 WTF??

```sh
$ ./lazyScanner.py 
OS Name - ubuntu, OS Version - 18
Total provided packages: 4397
Traceback (most recent call last):
  File "./lazyScanner.py", line 95, in <module>
    scanner.auditSystem()
  File "./lazyScanner.py", line 80, in auditSystem
    response = urllib2.urlopen(req, json.dumps(payload).encode('utf-8'))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 402: Payment Required
```

```sh
$ ./linuxScanner.py 
...
OS Name - ubuntu, OS Version - 18.04
Total found packages: 4397
Traceback (most recent call last):
  File "./linuxScanner.py", line 125, in <module>
    scannerInstance.scan(checkDocker=False)
...
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 402: Payment Required
```
